### ISSUE TITLE
Stop Criticizing me

### ISSUE THREAD

**Issue by Jerry080801** [HaHaWTH/AuthMeReReloaded#1]
### What behaviour is observed?

Stop Criticizing me

### Expected behaviour

Stop Criticizing me

### To Reproduce

Stop Criticizing me

### Plugin list

Stop Criticizing me

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

Stop Criticizing me

### Error log (if applicable)

Stop Criticizing me

### Configuration

Stop Criticizing me

**Comment by HaHaWTH** [comment]
.......What a u doing
