### ISSUE TITLE
SQLITE转换H2后email错误

### ISSUE THREAD

**Issue by 3328429240** [HaHaWTH/AuthMeReReloaded#100]
### AuthMe Version

41

### Error log (if applicable)

[AuthMe] Error during SQL operation: [JdbcSQLSyntaxErrorException]: (Message 42000 not found); SQL statement:
SELECT COUNT(1) FROM authme WHERE email = ? COLLATE NOCASE [42000-224]

**Comment by HaHaWTH** [comment]
Workflow #539 may fix this, have a try

**Comment by HaHaWTH** [comment]
Fixed in b42.
