### ISSUE TITLE
Add support for MiniMessage & other visual addons

### ISSUE THREAD

**Issue by SnowCutieOwO** [HaHaWTH/AuthMeReReloaded#102]
### What feature do you want to see added?

建议加入 MiniMessage 格式支持
另外把隔壁 UTitleAuth 那个登录显示标题/登录时显示BossBar(ActionBar)倒计时的功能集成一下最好

### Are there any alternatives?

N/A

### Anything else?

N/A

**Comment by HaHaWTH** [comment]
MiniMessage估计得把整个消息系统重写一遍，LoginTitle会尽快搞

**Comment by HaHaWTH** [comment]
Built-in support for Titles will break the compatibility of AuthMe, trying to resolve it.

**Comment by HaHaWTH** [comment]
Closed, same as #126.
Maybe reopen this when I am free?🤔

**Comment by HaHaWTH** [comment]
MiniMessage support is completed in branch feat/minimessage

**Comment by SnowCutieOwO** [comment]
> MiniMessage support is completed in branch feat/minimessage

我现在突然觉得把 MiniMessage 加进来[不是什么好事](https://github.com/WolfyScript/CustomCrafting/pull/369)了）

**Comment by F3F5** [comment]
> > MiniMessage support is completed in branch feat/minimessage
> 
> 我现在突然觉得把 MiniMessage 加进来[不是什么好事](https://github.com/WolfyScript/CustomCrafting/pull/369)了）

只需使用 Notepad++ 或 Visual Studio Code。
![Screenshot_6](https://github.com/HaHaWTH/AuthMeReReloaded/assets/170719238/5b8f6694-6253-432c-9213-2e482754d827)
