### ISSUE TITLE
Disable the ability for players to suggest player names as password

### ISSUE THREAD

**Issue by SnowCutieOwO** [HaHaWTH/AuthMeReReloaded#108]
### What feature do you want to see added?

如标题所示，禁止玩家在注册或修改密码时以在线玩家名称为密码
按道理来讲这一块的自动补全是应该被禁止的

### Are there any alternatives?

N/A

**Comment by HaHaWTH** [comment]
Confirmed.

**Comment by Dreeam-qwq** [comment]
在 `paper-global.yml` 或者 `paper.yml` 里关闭 `suggest-player-names-when-null-tab-completions`

**Comment by SnowCutieOwO** [comment]
> 在 `paper-global.yml` 或者 `paper.yml` 里关闭 `suggest-player-names-when-null-tab-completions`

denied
别的地方要用，单独让authme修一修没什么大不了

**Comment by HaHaWTH** [comment]
Completed. Next release will fix this.
