### ISSUE TITLE
支持Bungee与信息

### ISSUE THREAD

**Issue by psoloi** [HaHaWTH/AuthMeReReloaded#125]
### What feature do you want to see added?

能支持 **Bungee** 不让一些**传送插件**与**喊话插件**出现在**聊天框**里,防止玩家 **逃避登陆或注册** ,其次就是能加一个 **welcome.txt** 类似AuthMeReload的功能吗,还有能加 **\n** 内容换行这样的功能吗(类似就可以 **"|-: "** 这样格式的信息也不错)

### Are there any alternatives?

也能看**AuthMeReloadBungee**插件,支持这个插件也不错

### Anything else?

AuthMeReReload不支持 **\n** 内容换行这样的功能

**Comment by HaHaWTH** [comment]
> ### What feature do you want to see added?
> 能支持 **Bungee** 不让一些**传送插件**与**喊话插件**出现在**聊天框**里,防止玩家 **逃避登陆或注册** ,其次就是能加一个 **welcome.txt** 类似AuthMeReload的功能吗,还有能加 **\n** 内容换行这样的功能吗(类似就可以 **"|-: "** 这样格式的信息也不错)
> 
> ### Are there any alternatives?
> 也能看**AuthMeReloadBungee**插件,支持这个插件也不错
> 
> ### Anything else?
> AuthMeReReload不支持 **\n** 内容换行这样的功能

请在config.yml中打开bungeecord的hook，在Hooks配置栏下

关于换行，请参阅https://github.com/HaHaWTH/AuthMeReReloaded/blob/master/src/main/resources/messages/messages_zhcn.yml
