### ISSUE TITLE
登录显示title

### ISSUE THREAD

**Issue by postyizhan** [HaHaWTH/AuthMeReReloaded#126]
### What feature do you want to see added?

有个附属提供这个功能：https://www.spigotmc.org/resources/.111370

但插件本身提供就更好了

### Are there any alternatives?

https://www.spigotmc.org/resources/.111370

**Comment by HaHaWTH** [comment]
Duplicate to #102 , Will think about this

**Comment by HaHaWTH** [comment]
Currently, built-in support for title and actionbars will break the compatibility of AuthMe, will try XSeries

**Comment by HaHaWTH** [comment]
Extensions have supported this already, I think there's no need to add this feature.
Also I am not sure that I could do better than AuthMeTitle(
