### ISSUE TITLE
o神联系方式加不上

### ISSUE THREAD

**Issue by xiaoluofa** [HaHaWTH/AuthMeReReloaded#137]
### What feature do you want to see added?

想要一个自定义命令插件
可以执行一系列命令
读取placeholderapi

### Are there any alternatives?

~

**Comment by HaHaWTH** [comment]
Contact me via qq: 2509055917

**Comment by HaHaWTH** [comment]
Send me ur QQ number plz

**Comment by xiaoluofa** [comment]
> Contact me via qq: 2509055917

3782698642
