### ISSUE TITLE
支持PlaceholderAPI占位符

### ISSUE THREAD

**Issue by qaz197418i** [HaHaWTH/AuthMeReReloaded#147]
### What feature do you want to see added?

希望可以添加papi占位符支持，以显示玩家的一些信息
例如：
玩家是否绑定邮箱，返回true/false
玩家当前绑定的邮箱
玩家当前绑定的邮箱缩略，例如862******@qq.com，min*****@gmail.com会省略一些信息
玩家的注册时间
玩家注册的账号数量
等

### Are there any alternatives?

无

**Comment by HaHaWTH** [comment]
Nice suggestion!

**Comment by HaHaWTH** [comment]
Completed in 731c647
