### ISSUE TITLE
 ឵឵឵

### ISSUE THREAD

**Issue by F3F5** [HaHaWTH/AuthMeReReloaded#150]
### What behaviour is observed?

 ឵឵឵

### Expected behaviour

 ឵឵឵

### To Reproduce

 ឵឵឵

### Plugin list

 ឵឵឵

### Server Implementation

Standalone(Spigot)

### Database Implementation

SQLite

### AuthMe Version

 ឵឵឵

### Error log (if applicable)

 ឵឵឵

### Configuration

 ឵឵឵

**Comment by HaHaWTH** [comment]
No.

**Comment by Dreeam-qwq** [comment]
Yes, I understand.
