### ISSUE TITLE
switch to gradle kotlin

### ISSUE THREAD

**Issue by F3F5** [HaHaWTH/AuthMeReReloaded#163]
### What feature do you want to see added?

.

### Are there any alternatives?

.

### Anything else?

.

**Comment by TheFloodDragon** [comment]
It sounds nice!

It's also a good choice to divide different parts from the heavy plugin.

And more advanced and modern management, the Gradle can do this easily.

**Comment by HaHaWTH** [comment]
A great idea! But currently I need to keep up with upstream repository, gradle migration will be considered at a low priority.

**Comment by DongShaoNB** [comment]
Great! I like it

**Comment by Dreeam-qwq** [comment]
Thank you for your glowing and brilliant idea to switch our build system from Maven to Gradle Kotlin DSL. I fully support this idea and appreciate your initiative in proposing it. Gradle, especially with Kotlin DSL, offers several advantages over Maven, including improved build performance, better support for incremental builds, and a more modern, expressive scripting language. The use of Kotlin DSL can also enhance the readability and maintainability of our build scripts, making them easier to understand and modify. Additionally, Gradle's rich plugin ecosystem and superior dependency management capabilities can streamline our build processes and reduce configuration complexity. Transitioning to Gradle Kotlin will align our project with current industry standards and practices, ensuring we leverage the latest tools and techniques to enhance our development workflow. I believe this change will bring significant benefits to our team, improving both efficiency and productivity. I am excited about the potential improvements this transition can bring and look forward to collaborating on the implementation. Thank you once again for your valuable suggestion and commitment to the project's success. Let's move forward with evaluating and planning this migration.
