### ISSUE TITLE
commands.yml fixes

### ISSUE THREAD

**Issue by ImKarven** [HaHaWTH/AuthMeReReloaded#170]
### What behaviour is observed?

Any command executed in commands.yml are not async and causes errors.

### Expected behaviour

It should work normally

### To Reproduce

go to commands.yml in plugin dir.
add any command related to region threading (/tp (through regions), etc) to any action you want
do that action in game
look at console

### Plugin list

not related

### Server Implementation

Standalone(Folia)

### Database Implementation

SQLite

### AuthMe Version

5.6.0 b50

### Configuration

not related

**Comment by HaHaWTH** [comment]
Fixed in 9b74cb
