### ISSUE TITLE
Illegal Characters only when Registering on Geyser/Bedrock

### ISSUE THREAD

**Issue by brian-g12** [HaHaWTH/AuthMeReReloaded#197]
### What behaviour is observed?

When a player using bedrock tries to register, they get an error that says their password has "illegal characters" even though they are using characters defined in regex.

### Expected behaviour

It lets them register like on Java.

### To Reproduce

Login with a bedrock account and try to register, you will get stuck at password

### Plugin list

Bedrock/Geyser 

### Server Implementation

Standalone(Spigot)

### Database Implementation

SQLite

### AuthMe Version

5.6.0

### Error log (if applicable)

None

### Configuration

https://gist.github.com/brian-g12/f9ab8a360b43c98e70a38ee98d839835

**Comment by HaHaWTH** [comment]
Looks same as #200, try enabling Hooks.floodgate in the config.
