### ISSUE TITLE
Stop Criticizing me

### ISSUE THREAD

**Issue by Jerry080801** [HaHaWTH/AuthMeReReloaded#2]
### What behaviour is observed?

Stop Criticizing me

### Expected behaviour

Stop Criticizing meStop Criticizing me

### To Reproduce

Stop Criticizing me

### Plugin list

Stop Criticizing me

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

Stop Criticizing me

### Configuration

Stop Criticizing me

**Comment by HaHaWTH** [comment]
go away
