### ISSUE TITLE
Illegal Character Issue on Bedrock users

### ISSUE THREAD

**Issue by WingsStroke** [HaHaWTH/AuthMeReReloaded#200]
### What behaviour is observed?

Some Bedrock players, who meet the requirements in their usernames, cannot enter the server directly, nor can they register.
![Illegal Character issue plugin server](https://github.com/user-attachments/assets/dbc550fb-b7cd-465a-8cf5-5d5ec6cc246a)

### Expected behaviour

Possibly players with capital letters in their usernames, even though the server allows names with capital letters

### To Reproduce

1. Bedrock Players with capital letters enter to the server
2. The Issue appears.

### Plugin list

AuraSkills, AuthMe, floodgate, Geyser-Spigot, LevelledMobs, LuckPerms, sleep-most

### Server Implementation

Standalone(Spigot)

### Database Implementation

SQLite

### AuthMe Version

v5.7.0-FORK

### Configuration

https://cdn.discordapp.com/attachments/1106756561134682123/1274533254401097758/config.yml?ex=66c29917&is=66c14797&hm=3314062786b6139d947f93cd0371a83ac56b4c775fd2c80ef2139405372bb3f7&

**Comment by HaHaWTH** [comment]
Enable Hooks.floodgate in the config and try again

**Comment by WingsStroke** [comment]
> Enable Hooks.floodgate in the config and try again



> Enable Hooks.floodgate in the config and try again

Thanks
