### ISSUE TITLE
[Paper core] Player still ghost after using defaul AuthMe

### ISSUE THREAD

**Issue by Oxibaros** [HaHaWTH/AuthMeReReloaded#206]
### What behaviour is observed?

I started using AuthMe, but immediately some of the players became Ghost. I thought downloading this plugin would automatically solve this problem. But no. I spent a lot of time, but still did not find a solution.

### Expected behaviour

Find a way to "unghost" players

### To Reproduce

1. Download AuthMe
2. Player become ghosts
3. Download this plugin, and remove AuthMe
4. Problem not fixed
_5. Lose hope_

### Plugin list

![image](https://github.com/user-attachments/assets/458b981a-0d4c-43e2-b065-a565c38744ac)

### Server Implementation

Standalone(Spigot)

### Database Implementation

SQLite

### AuthMe Version

AuthMeReloaded v5.7.0-FORK

### Configuration

https://paste.gg/p/anonymous/79d2677933324dce94cfea6fe60b6c41

**Comment by Oxibaros** [comment]
`anti GhostPlayer: true` doesn't solve problem

**Comment by HaHaWTH** [comment]
Can you provide any screenshots for players being ghost?

**Comment by Oxibaros** [comment]
> Can you provide any screenshots for players being ghost?

![image](https://github.com/user-attachments/assets/99aba0c0-bf4b-4ce0-a2e8-4cd27e174fb1)
Player without effects

**Comment by HaHaWTH** [comment]
I think it's not caused by AuthMe tbh, AuthMe never touches this thing. Are you sure this happened after installing AuthMe?

**Comment by Oxibaros** [comment]
> I think it's not caused by AuthMe tbh, AuthMe never touches this thing. Are you sure this happened after installing AuthMe?

Sure. I used Librelogin, but this plugin doesn't quite fit (boats disapointed in Limbo world, one user have same problem, but author does not answer in git). Decided to change it to Authme, and immediately ran into this problem.

This problem did not exist before

**Comment by Oxibaros** [comment]
Forgot to add that I tried force login, player registration, etc. And when this problem arose, he was running around the world, but he was not registered. He himself could not register, because he seemed to be logged in, but it was not possible to forcibly log him in, because he was not registered. After I registered it, it crashed from the server, but the problem persisted.

**Comment by Oxibaros** [comment]
**Not relevant.** Problem not solved
