### ISSUE TITLE
Players sometimes die when they're kicked due to time out, "Attempt to teleport removed player restricted"?

### ISSUE THREAD

**Issue by HidekoHaruna** [HaHaWTH/AuthMeReReloaded#209]
### What behaviour is observed?

(The server is running Paper 1.21)

Sometimes, when a player is kicked due to timing out (which usually happens when someone's got bad wifi) they see the death screen when they log in. Other players can see the death message, which usually says the player got killed by a mob. I had this happen to me personally and I also happened to have a minimap/waypoint mod installed then, and when I checked out the death waypoint, it appeared about 15 blocks under the server spawn. Like, 15 blocks deep in the ground. And if the player had any items on them, they disappear completely. I know this all sounds unrelated to authme, but I checked the logs and noticed it says "Attempt to teleport removed player [username] restricted". So, is this all because authme fails to teleport the player when they log in?

Update: Apparently it resets your enderchest too. Maybe it resets the entire playerdata?

### Expected behaviour

I'd expect the plugin to kick the player properly, and when they relog, return them safely to where they were before.

### To Reproduce

1. Have bad internet
2.  Get "Timed Out" (kicked out of the server)
3. Log back in

### Plugin list

Authme, ClaimChunk, DriveBackupV2, FarmControl, HaoNick, LuckPerms, NickAPI, PerWorldPlugins, PlaceholderAPI, ProtocolLib, SentinelAI, Sit, SkinsRestorer, Spawn, WorldEdit, WorldGuard

### Server Implementation

Standalone(Spigot)

### Database Implementation

SQLite

### AuthMe Version

AuthMeReloaded v5.7.0-FORK (build: 52)

### Error log (if applicable)

https://paste.gg/p/anonymous/94ad950b386f4cf4ac71ba009b3baa3f

### Configuration

https://paste.gg/p/anonymous/cca2370253c048a5b2201735c2a14ec7

**Comment by HaHaWTH** [comment]
Update please, b53 fixed this :)
