### ISSUE TITLE
插件屏蔽玩家加入离开消息

### ISSUE THREAD

**Issue by chengjy123** [HaHaWTH/AuthMeReReloaded#230]
### What behaviour is observed?

插件版本5.7.0，本插件与EssentialsX一起使用时会屏蔽EssentialsX插件的玩家加入与离开服务器的消息

### Expected behaviour

显示玩家加入和离开的消息

### To Reproduce

authme与EssentialsX一起启动

### Plugin list

AuthMe, Essentials, EssentialsChat, EssentialsSpawn, Multiverse-Core, ProtocolLib, Sleeper, Vault

### Server Implementation

Standalone(Spigot)

### Database Implementation

SQLite

### AuthMe Version

5.7.0

### Configuration

<script src="https://gist.github.com/chengjy123/3235244ea44c39378439296fd0184528.js"></script>

**Comment by HaHaWTH** [comment]
removeLeaveMessage
removeJoinMessage
这两项关闭
