### ISSUE TITLE
[Folia] Bug, when enable teleportUnAuthedToSpawn, SaveQuitLocation.

### ISSUE THREAD

**Issue by Chiro145** [HaHaWTH/AuthMeReReloaded#3]
### What behaviour is observed?

my distance to spawn is 16k blocks

### Expected behaviour

My character is freeze, not can break, chat, place, etc...

### To Reproduce

1\ enable teleportUnAuthedToSpawn, SaveQuitLocation.
2\ set authme spawn to 0 75 0
3\ then go to 10000 80 -6000 as far spawn as possible
4\ then reconnect server

### Plugin list

[13:36:07 INFO]: Server Plugins (2):
[13:36:07 INFO]: Bukkit Plugins:
[13:36:07 INFO]:  - AuthMe, NoCheatPlus

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

AuthMe-5.6.0-FORK-Folia

### Error log (if applicable)

https://paste.gg/p/anonymous/22bdd489edb748e7bc69cdcc02544765

### Configuration

https://paste.gg/p/anonymous/8b7da60182bf4445b732ee42f3321c7e

**Comment by HaHaWTH** [comment]
I see.This issue is in WIP,i am trying to resolve it,hold on please:-)

**Comment by HaHaWTH** [comment]
Now I mainly work on Spigot version,I may spend less time on folia ver, so the issue may be fixed a bit slowly, sorry:), before i fix this, you can disable teleportUnAuthedToSpawn to temporarily avoid this issue, thanks a lot for you feedback

**Comment by HaHaWTH** [comment]
Maybe I have fixed this issue, but it still requires some tests :-)

**Comment by HaHaWTH** [comment]
Ah..... There are some problems due to the API changes, it may take me a while to fix it:-(

**Comment by HaHaWTH** [comment]
We have fixed it!!!!
