### ISSUE TITLE
[Feature]plz update Folia build of AuthMe-5.6.0-Fork-b35 

### ISSUE THREAD

**Issue by Moranyixiao** [HaHaWTH/AuthMeReReloaded#75]
### What feature do you want to see added?

plz update Folia build of AuthMe-5.6.0-Fork-b35 

### Are there any alternatives?

plz update Folia build of AuthMe-5.6.0-Fork-b35

**Comment by HaHaWTH** [comment]
Folia is at low priority, maybe update in near future.

**Comment by HaHaWTH** [comment]
Will do this after main features are implemented.

**Comment by HaHaWTH** [comment]
Now working on this

**Comment by HaHaWTH** [comment]
Folia supported.
