### ISSUE TITLE
[Bug]在release下载的b37版本，插件加载时显示b36

### ISSUE THREAD

**Issue by Midnight-2004** [HaHaWTH/AuthMeReReloaded#76]
### What behaviour is observed?

如题，我在Github的release里下载的b37，插件加载后显示版本为b36
<img width="639" alt="image" src="https://github.com/HaHaWTH/AuthMeReReloaded/assets/98314538/29a90f50-51ad-40eb-882f-92d25b429865">

### Expected behaviour

其应该为b37版本

### To Reproduce

1.从release下载b37版本的插件并放入服务端
2.启动服务器
3.加载插件时显示消息：
```
[09:30:46 WARN]: [AuthMe] New version available! Latest:b37 Current:b36
[09:30:46 WARN]: [AuthMe] Download from here: github.com/HaHaWTH/AuthMeReReloaded/releases/latest
```
4.在控制台执行命令  authme version 显示版本为`Version: AuthMeReloaded v5.6.0-FORK (build: 36)`

### Plugin list

 AuthMe, CoreProtect, Essentials, GroupManager, GSit, Ip2region, PlaceholderAPI, PlayerChat, PlayerMenu, PlayerTitle，PowerBoard, PublicBin, ServerListMotdSpigot, SkinsRestorer, TAB, ViaBackwards, ViaVersion, ViewSlimeChunk, WorldEdit

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

AuthMeReloaded v5.6.0-FORK (build: 36)

### Configuration

--

**Comment by HaHaWTH** [comment]
Thanks, will be fix soon

**Comment by HaHaWTH** [comment]
Reuploaded, please download the latest release
