### ISSUE TITLE
 [bug] All issues of teleportUnAuthedToSpawn

### ISSUE THREAD

**Issue by ghost** [HaHaWTH/AuthMeReReloaded#78]
### What behaviour is observed?

Just check https://github.com/AuthMe/AuthMeReloaded/issues/2769

### Expected behaviour

.

### To Reproduce

.

### Plugin list

.

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

from actions (today)

### Error log (if applicable)

.

### Configuration

.

**Comment by HaHaWTH** [comment]
I see. I will look into it :0

**Comment by F3F5** [comment]
> I see. I will look into it :0

plugin nlogin fixed all issues (for example to you)

**Comment by HaHaWTH** [comment]
I tried to fix the y=0 teleport issue last weekend, it got worse:(
Maybe AuthMe records the quit location of players who first logged in on y=0?

**Comment by F3F5** [comment]
i dont think so

**Comment by HaHaWTH** [comment]
> i dont think so

Do you know how to add H2 database support? I tried hard to add H2 support last month, but failed. :(

**Comment by F3F5** [comment]
what progress

**Comment by HaHaWTH** [comment]
Working on #57 Y=0 teleport issue

**Comment by F3F5** [comment]
did better my plugin https://github.com/F3F5/SpawnAuth without bugs, you can recode authme's hide location and use something from my plugib

**Comment by Waenara** [comment]
Up

**Comment by StasM1X** [comment]
Up

**Comment by HaHaWTH** [comment]
I see, will look into it after I finished my another project AdvancedSensitiveWords

**Comment by F3F5** [comment]
> did better my plugin https://github.com/F3F5/SpawnAuth without bugs, you can recode authme's hide location and use something from my plugin

plugin recoded and now it work good

**Comment by HaHaWTH** [comment]
y = 0 teleport bug is now fixed.

**Comment by HaHaWTH** [comment]
> > did better my plugin https://github.com/F3F5/SpawnAuth without bugs, you can recode authme's hide location and use something from my plugin
> 
> plugin recoded and now it work good

y = 0 teleport bug is now fixed.

**Comment by F3F5** [comment]
nice

**Comment by HaHaWTH** [comment]
Issue 1 seems fixed, need more tests

**Comment by HaHaWTH** [comment]
Fixed, will push after upstream has updated
