### ISSUE TITLE
[feature] Use a normal build without integration with China

### ISSUE THREAD

**Issue by F3F5** [HaHaWTH/AuthMeReReloaded#79]
### What feature do you want to see added?

And default settings like AuthMe. Hope you hear me.

### Are there any alternatives?

AuthMe

**Comment by HaHaWTH** [comment]
Got it, I'll do it soon.

**Comment by HaHaWTH** [comment]
Finished in 528b61c

**Comment by F3F5** [comment]
fogort about this     messagesLanguage: zhcn
 @HaHaWTH

**Comment by HaHaWTH** [comment]
> fogort about this messagesLanguage: zhcn @HaHaWTH

in 9daf44d
