### ISSUE TITLE
[bug] missing key

### ISSUE THREAD

**Issue by ghost** [HaHaWTH/AuthMeReReloaded#81]
### What behaviour is observed?

[08:09:05] [Server thread/INFO]: [AuthMe] Added 1 missing keys to your messages_xx.yml file: [registration.kicked_admin_registered]

### Expected behaviour

after first start server i see this

### To Reproduce

,

### Plugin list

,

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

from actions (today)

### Error log (if applicable)

,

### Configuration

,

**Comment by F3F5** [comment]
why changed file messages_zhcn.yml but it says messages_xx.yml @HaHaWTH

**Comment by HaHaWTH** [comment]
> why changed file messages_zhcn.yml but it says messages_xx.yml @HaHaWTH

Emmm...I only add this messageKey for zhcn and en:(
