### ISSUE TITLE
shift+f快捷键设置导致f键切换主副手失灵

### ISSUE THREAD

**Issue by xiaoxiaoyuqiyu2022** [HaHaWTH/AuthMeReReloaded#89]
### What behaviour is observed?

配置文件config.yml中的
3rdPartyFeature:
    compatibility:
        menuPlugins: false/true 设置成false会导致f键切换主副手失灵,设置成true择导致其他插件无法使用shift+f这一快捷键

### Expected behaviour

正常来说应该设置为false后插件不再影响shift+f功能了，但却发生了f键无法切换主副手

### To Reproduce

1，将config中的3rdPartyFeature:
    compatibility:
        menuPlugins: 设置成false
2.进入游戏，重载authmerereloaded插件，按下f键，发现无法切换主副手
3.将插件删除，重启服务端
4.进入游戏，按下f键，发现主副手切换恢复正常

### Plugin list

Server Plugins (30):
Paper Plugins:
- BKCommonLib
Bukkit Plugins:
- AifadianPay, AuthMe, CMI, CMILib, Craftorithm, CustomCrops, CustomFishing, CustomNameplates, DailyStore, DecentHolograms
GardenBank, InfiniteScoreboard, ItemsAdder, LoneLibs, LuckPerms, mc-go-cqhttp, mgc-CodeWhiteList, My_Worlds, PlaceholderAPI, ProtocolLib
RealisticSeasons, TrChat, TrMenu, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldProtecion, YukiNoaAPI

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

AuthMe-5.6.0-Fork-b39

### Configuration

https://paste.gg/p/anonymous/07ad941dbc8140119e32cc10c6219828

**Comment by HaHaWTH** [comment]
Fixed in a9cb2d
